# Generated by Django 4.2.1 on 2023-05-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_article_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="img2",
        ),
        migrations.AlterField(
            model_name="article",
            name="img",
            field=models.TextField(default=""),
        ),
    ]
