# Generated by Django 4.2 on 2023-06-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_article_count_reads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
    ]
