# Generated by Django 4.2 on 2023-06-13 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_article_img"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
