# Generated by Django 4.2.2 on 2023-06-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitmodel",
            name="execution_time",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="visitmodel",
            name="user",
            field=models.CharField(default="", null=True),
        ),
    ]
