# Generated by Django 4.2.2 on 2023-06-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_is_admin_myuser_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
