# Generated by Django 4.2.2 on 2023-06-20 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_myuser_is_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="is_staff",
        ),
    ]
