# Generated by Django 4.2.2 on 2023-06-20 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_myuser_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="created_ad",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
