# Generated by Django 4.2.2 on 2023-06-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_myuser_created_ad"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatar/no_avatar.jpg",
                null=True,
                upload_to="avatar",
            ),
        ),
    ]
